### ISSUE TITLE
TypeError: js2xmlparser is not a function

### ISSUE THREAD

**Issue by rajajlidi** [grishick/zimbra-client#10]
can someone help me

var express= require('express');
var router= express.Router();
var js2xmlparser = require("js2xmlparser");

var zimbra = require("zimbra-client");

var ZIMBRA_HOST = "localhost";
var ADMIN_LOGIN = "admin";
var ADMIN_PWD = "qwe123@";
var domain = "dc.esweb.com.br";
var userEmail = "test@esweb.com.br";

//get an authtoken

zimbra.getAdminAuthToken(ZIMBRA_HOST, ADMIN_LOGIN, ADMIN_PWD,
    function(err, authToken) {
        if(err != null) {
            console.log(err.message);
        } else {
            //create a damain using authtoken passed on by getAuthToken
            zimbra.createDomain(ZIMBRA_HOST, domain, {description:"test domain"}, authToken,
                function (err1, respObj) {
                    if (err1 != null) {
                        if (err1.code == "account.DOMAIN_EXISTS") {
                            console.log("Domain with this name already exists");
                        } else {
                            console.log(err1.message);
                        }
                    } else {
                        console.log("Created domain: " + respObj.name);
                        //create an account using the same authtoken passed on buy getAuthToken
                        createAccount(ZIMBRA_HOST,{sn:"raja",givenName:"raja",displayName:"raja",password:"qwe123@",name:userEmail},authToken,
                            function(err1,accountObj) {
                                if(err1 != null) {
                                    if(err1.code == "account.ACCOUNT_EXISTS") {
                                        console.log("an account with this name already exists");
                                    } else
                                    {
                                        console.log(err1.message);
                                    }
                                } else {
                                    console.log("new account ID" + accountObj.id);
                                }
                            }
                        );
                    }
                });
        }
    });

module.exports=router;

**Comment by grishick** [comment]
This should be fixed in version 0.0.14. I have just pushed the update to NPM
