### ISSUE TITLE
TypeError: js2xmlparser is not a function

### ISSUE THREAD

**Issue by rajajlidi** [grishick/zimbra-client#9]
when i try to create account , after run i get this error
   return js2xmlparser("soap:Envelope",soapReq);

this is my code 
var express= require('express');
var router= express.Router();
var js2xmlparser = require("js2xmlparser");

var zimbra = require("zimbra-client");

zimbra.getAdminAuthToken("localhost", "admin", "qwe123@",
    function(err, authToken) {
        if(err != null) {
            console.log(err.message);
        }
        zimbra.createAccount("localhost",{sn:"rajaaa",givenName:"raj",displayName:"rajaaa raj",password:"qwe123@",name:"admin@dc.esweb.com.br"},authToken,
            function(err1,accountObj) {
                if(err1 != null) {
                    if(err1.code == "account.ACCOUNT_EXISTS") {
                        console.log("an account with this name already exists");
                    } else {
                        console.log(err1.message);
                    }
                } else {
                    console.log("new account ID" + accountObj.id);
                }
            }
        );
    })

module.exports=router;

**Comment by grishick** [comment]
This should be fixed in version 0.0.14. I have just pushed the update to NPM
